In [61]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [62]:
options = Options()
options.add_argument("--disable-notifications")
options.add_argument("--disable-popup-blocking")
driver = webdriver.Chrome(options=options)

In [63]:
league_url = 'https://fbref.com/en/comps/9/Premier-League-Stats'

In [65]:
years = years = list(range(2024, 2009, -1))
tables=[]
years

[2024,
 2023,
 2022,
 2021,
 2020,
 2019,
 2018,
 2017,
 2016,
 2015,
 2014,
 2013,
 2012,
 2011,
 2010]

In [66]:
for year in years:

    driver.get(league_url)
    data = requests.get(league_url)
    soup = BeautifulSoup(data.text)
    print(league_url)
    time.sleep(2)
         
    try:
        driver.find_element(By.CSS_SELECTOR, 'button[mode=primary]').click()
    except Exception:
        pass

    previous_season = soup.select("div.prevnext a")[0].get("href")

    table = pd.read_html(league_url, match="Regular season Table")[0]
    table["Season"] = year
    tables.append(table)

    league_url = f"https://fbref.com{previous_season}"


driver.quit()

https://fbref.com/en/comps/9/Premier-League-Stats
https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats
https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats
https://fbref.com/en/comps/9/2020-2021/2020-2021-Premier-League-Stats
https://fbref.com/en/comps/9/2019-2020/2019-2020-Premier-League-Stats
https://fbref.com/en/comps/9/2018-2019/2018-2019-Premier-League-Stats
https://fbref.com/en/comps/9/2017-2018/2017-2018-Premier-League-Stats
https://fbref.com/en/comps/9/2016-2017/2016-2017-Premier-League-Stats
https://fbref.com/en/comps/9/2015-2016/2015-2016-Premier-League-Stats
https://fbref.com/en/comps/9/2014-2015/2014-2015-Premier-League-Stats
https://fbref.com/en/comps/9/2013-2014/2013-2014-Premier-League-Stats
https://fbref.com/en/comps/9/2012-2013/2012-2013-Premier-League-Stats
https://fbref.com/en/comps/9/2011-2012/2011-2012-Premier-League-Stats
https://fbref.com/en/comps/9/2010-2011/2010-2011-Premier-League-Stats
https://fbref.com/en/comps/9/2009-2010/2009-2010-Premier-League-Stats

In [67]:
table = pd.concat(tables)

In [68]:
table

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,...,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,Season
0,1,Manchester City,37,27,7,3,93,33,60,88,...,78.6,35.2,43.4,1.17,W W W W W,52896,Erling Haaland - 27,Ederson,NaN,2024
1,2,Arsenal,37,27,5,5,89,28,61,86,...,73.2,27.3,45.9,1.24,W W W W W,60232,Bukayo Saka - 16,David Raya,NaN,2024
2,3,Liverpool,37,23,10,4,84,41,43,79,...,83.3,45.3,38.0,1.03,W L D W D,55753,Mohamed Salah - 18,Alisson,NaN,2024
3,4,Aston Villa,37,20,8,9,76,56,20,68,...,62.5,57.4,5.1,0.14,W W D L D,41858,Ollie Watkins - 19,Emiliano Mart√≠nez,NaN,2024
4,5,Tottenham,37,19,6,12,71,61,10,63,...,65.1,62.4,2.6,0.07,L L L W L,61482,Son Heung-min - 17,Guglielmo Vicario,NaN,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,16,Wigan Athletic,38,9,9,20,37,79,-42,36,...,NaN,NaN,NaN,NaN,NaN,18006,Hugo Rodallega - 10,Chris Kirkland,NaN,2010
16,17,West Ham,38,8,11,19,47,66,-19,35,...,NaN,NaN,NaN,NaN,NaN,33683,Carlton Cole - 10,Robert Green,NaN,2010
17,18,Burnley,38,8,6,24,42,82,-40,30,...,NaN,NaN,NaN,NaN,NaN,20654,Steven Fletcher - 8,Brian Jensen,Relegated,2010
18,19,Hull City,38,6,12,20,34,75,-41,30,...,NaN,NaN,NaN,NaN,NaN,24390,Stephen Hunt - 6,Boaz Myhill,Relegated,2010
19,20,Portsmouth,38,7,7,24,34,66,-32,19,...,NaN,NaN,NaN,NaN,NaN,18249,Aruna Dindane - 8,David James,"9-point deduction 3, Relegated",2010

In [69]:
table = table.drop(["Last 5", "Goalkeeper", "Notes"], axis=1)
table = table.reset_index()
table = table.drop('index', axis=1)

In [70]:
table

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Season
0,1,Manchester City,37,27,7,3,93,33,60,88,2.38,78.6,35.2,43.4,1.17,52896,Erling Haaland - 27,2024
1,2,Arsenal,37,27,5,5,89,28,61,86,2.32,73.2,27.3,45.9,1.24,60232,Bukayo Saka - 16,2024
2,3,Liverpool,37,23,10,4,84,41,43,79,2.14,83.3,45.3,38.0,1.03,55753,Mohamed Salah - 18,2024
3,4,Aston Villa,37,20,8,9,76,56,20,68,1.84,62.5,57.4,5.1,0.14,41858,Ollie Watkins - 19,2024
4,5,Tottenham,37,19,6,12,71,61,10,63,1.70,65.1,62.4,2.6,0.07,61482,Son Heung-min - 17,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,16,Wigan Athletic,38,9,9,20,37,79,-42,36,0.95,NaN,NaN,NaN,NaN,18006,Hugo Rodallega - 10,2010
296,17,West Ham,38,8,11,19,47,66,-19,35,0.92,NaN,NaN,NaN,NaN,33683,Carlton Cole - 10,2010
297,18,Burnley,38,8,6,24,42,82,-40,30,0.79,NaN,NaN,NaN,NaN,20654,Steven Fletcher - 8,2010
298,19,Hull City,38,6,12,20,34,75,-41,30,0.79,NaN,NaN,NaN,NaN,24390,Stephen Hunt - 6,2010
299,20,Portsmouth,38,7,7,24,34,66,-32,19,0.50,NaN,NaN,NaN,NaN,18249,Aruna Dindane - 8,2010

In [71]:
table.to_csv("C:/Users/tomas.hehir/Source/Repos/Footy/data/PL/0910-2324PLTable.csv")